export const ADD_MOVIE_FILTER = "ADD_MOVIE_FILTER";
export const REMOVE_MOVIE_FILTER = "REMOVE_MOVIE_FILTER";

export const ADD_SERIES_FILTER = "ADD_SERIES_FILTER";
export const REMOVE_SERIES_FILTER = "REMOVE_SERIES_FILTER";

export const MOVIE_ACTIVE = "MOVIE_ACTIVE";
export const MOVIE_INACTIVE = "MOVIE_INACTIVE";

export const SERIES_ACTIVE = "SERIES_ACTIVE";
export const SERIES_INACTIVE = "SERIES_INACTIVE";

export const GET_MOVIE_TYPE_REQUEST = "GET_MOVIE_TYPE_REQUEST";
export const GET_MOVIE_TYPE_SUCCESS = "GET_MOVIE_TYPE_SUCCESS";
export const GET_MOVIE_TYPE_ERROR = "GET_MOVIE_TYPE_ERROR";

export const GET_SERIES_TYPE_REQUEST = "GET_SERIES_TYPE_REQUEST";
export const GET_SERIES_TYPE_SUCCESS = "GET_SERIES_TYPE_SUCCESS";
export const GET_SERIES_TYPE_ERROR = "GET_SERIES_TYPE_ERROR";

export const ADD_TO_WATCH_LIST = "ADD_TO_WATCH_LIST";
export const REMOVE_FROM_WATCH_LIST = "REMOVE_FROM_WATCH_LIST";
export const CLEAR_WATCH_LIST = "CLEAR_WATCH_LIST";

export const GET_LIST_ITEM_REQUEST = "GET_LIST_ITEM_REQUEST";
export const GET_LIST_ITEM_SUCCESS = "GET_LIST_ITEM_SUCCESS";
export const GET_LIST_ITEM_ERROR = "GET_LIST_ITEM_ERROR";

export const ADD_TO_MOVIE_LIST = "ADD_TO_MOVIE_LIST";
export const REMOVE_FROM_MOVIE_LIST = "REMOVE_FROM_MOVIE_LIST";

export const ADD_TO_TV_LIST = "ADD_TO_TV_LIST";
export const REMOVE_FROM_TV_LIST = "REMOVE_FROM_TV_LIST";

export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_ERROR = "GET_SEARCH_ERROR";

export const REMOVE_SEARCH = "REMOVE_SEARCH";

export const ADD_NEW_LINK = "ADD_NEW_LINK";
