export const ADD_MOVIE_FILTER = "ADD_MOVIE_FILTER";
export const REMOVE_MOVIE_FILTER = "REMOVE_MOVIE_FILTER";

export const ADD_SERIES_FILTER = "ADD_SERIES_FILTER";
export const REMOVE_SERIES_FILTER = "REMOVE_SERIES_FILTER";

export const MOVIE_ACTIVE = "MOVIE_ACTIVE";
export const MOVIE_INACTIVE = "MOVIE_INACTIVE";

export const SERIES_ACTIVE = "SERIES_ACTIVE";
export const SERIES_INACTIVE = "SERIES_INACTIVE";

export const GET_MOVIE_TYPE_REQUEST = "GET_MOVIE_TYPE_REQUEST";
export const GET_MOVIE_TYPE_SUCCESS = "GET_MOVIE_TYPE_SUCCESS";
export const GET_MOVIE_TYPE_ERROR = "GET_MOVIE_TYPE_ERROR";

export const GET_SERIES_TYPE_REQUEST = "GET_SERIES_TYPE_REQUEST";
export const GET_SERIES_TYPE_SUCCESS = "GET_SERIES_TYPE_SUCCESS";
export const GET_SERIES_TYPE_ERROR = "GET_SERIES_TYPE_ERROR";
